### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by apatel762** [apatel762/workstation#2]
setting up a new computer:

write down every single step that I've done (into a note in the Obsidian vault) - some steps are written on paper need to copy them over

- [x] install updates
- [x] **pin the current deployment** using this command: `sudo ostree admin pin 0`
- [x] create an OS image in this repo and rebase onto it
- [x] update README with clear instructions

notes that were here before I co-opted this issue for other things

- `distrobox` - all my work is inside containers, so this is a must-have
- `code` - flatpak doesn't work well, installing it inside the container is hacky
- `keepassxc` - flatpak doesn't integrate with web browser
- `brave` - flatpak erases the managed config each time the browser is updated...
  - unless i can figure out how to use the policy extension point for flatpak's e.g. the one documented [here](https://github.com/flathub/com.github.Eloston.UngoogledChromium/tree/master) for ungoogled-chromium

nice to have

- [x] automatic updates
- [x] automatic updates (flatpak)
- [x] #5
